package baseline

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/glsec/glsec/internal/finding"
)

func write(t *testing.T, content string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "baseline")
	if err := os.WriteFile(p, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

func gl001(line int) finding.Finding {
	return finding.Finding{RuleID: "GL001", File: ".gitlab-ci.yml", Line: line, Message: `image "node:latest" uses mutable tag`}
}

func TestJSONSnapshot_MatchesByMessageIgnoringLine(t *testing.T) {
	p := write(t, `{"findings":[{"rule":"GL001","file":".gitlab-ci.yml","line":5,"message":"image \"node:latest\" uses mutable tag"}]}`)
	b, err := Load(p)
	if err != nil {
		t.Fatal(err)
	}
	// Same finding, drifted to a different line — must NOT be reported as new.
	if b.IsNew(gl001(12)) {
		t.Fatal("drifted baseline finding reported as new")
	}
}

func TestJSONSnapshot_DifferentMessageIsNew(t *testing.T) {
	p := write(t, `{"findings":[{"rule":"GL001","file":".gitlab-ci.yml","line":5,"message":"image \"node:latest\" uses mutable tag"}]}`)
	b, _ := Load(p)
	other := finding.Finding{RuleID: "GL001", File: ".gitlab-ci.yml", Line: 9, Message: `image "python:latest" uses mutable tag`}
	if !b.IsNew(other) {
		t.Fatal("finding with a different message should be new")
	}
}

func TestMultiplicity(t *testing.T) {
	p := write(t, `{"findings":[{"rule":"GL001","file":".gitlab-ci.yml","line":5,"message":"image \"node:latest\" uses mutable tag"}]}`)
	b, _ := Load(p)
	// One accepted occurrence absorbs the first; a second identical finding is new.
	if b.IsNew(gl001(5)) {
		t.Fatal("first occurrence should match baseline")
	}
	if !b.IsNew(gl001(5)) {
		t.Fatal("second identical occurrence should be new (count exhausted)")
	}
}

func TestIgnoreFileFormat_MatchesByRuleAndFile(t *testing.T) {
	p := write(t, "# Generated by glsec --generate-ignore\n.gitlab-ci.yml:5 GL001\n")
	b, err := Load(p)
	if err != nil {
		t.Fatal(err)
	}
	// No message available in .glsec-ignore, so match is rule+file, drift-tolerant.
	if b.IsNew(gl001(99)) {
		t.Fatal("baselined finding reported as new")
	}
	if !b.IsNew(finding.Finding{RuleID: "GL003", File: ".gitlab-ci.yml", Line: 5}) {
		t.Fatal("different rule should be new")
	}
}

func TestEmpty(t *testing.T) {
	if !Empty().IsNew(gl001(1)) {
		t.Fatal("empty baseline must report everything as new")
	}
}
